"""community

Revision ID: 0004_community
Revises: 0003_add_walk_path
Create Date: 2026-07-11

Adds the Community layer (design/COMMUNITY.md §3): users.handle/avatar_url/last_active_at
plus friendships, activity_events, challenges, challenge_participants. RLS for the new
tables is applied separately via db/rls.sql after `alembic upgrade head`.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004_community"
down_revision: str | Sequence[str] | None = "0003_add_walk_path"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_activity_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_events")),
    )
    op.create_index(
        op.f("ix_activity_events_created_at"), "activity_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_activity_events_user_id"), "activity_events", ["user_id"], unique=False
    )
    op.create_table(
        "challenges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("metric", sa.String(length=16), nullable=False),
        sa.Column("goal", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_challenges_creator_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_challenges")),
    )
    op.create_index(op.f("ix_challenges_creator_id"), "challenges", ["creator_id"], unique=False)
    op.create_table(
        "friendships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("addressee_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["addressee_id"],
            ["users.id"],
            name=op.f("fk_friendships_addressee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
            name=op.f("fk_friendships_requester_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_friendships")),
        sa.UniqueConstraint(
            "requester_id", "addressee_id", name=op.f("uq_friendships_requester_id")
        ),
    )
    op.create_index(
        op.f("ix_friendships_addressee_id"), "friendships", ["addressee_id"], unique=False
    )
    op.create_index(
        op.f("ix_friendships_requester_id"), "friendships", ["requester_id"], unique=False
    )
    op.create_table(
        "challenge_participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("challenge_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["challenges.id"],
            name=op.f("fk_challenge_participants_challenge_id_challenges"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_challenge_participants_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_challenge_participants")),
        sa.UniqueConstraint(
            "challenge_id", "user_id", name=op.f("uq_challenge_participants_challenge_id")
        ),
    )
    op.create_index(
        op.f("ix_challenge_participants_challenge_id"),
        "challenge_participants",
        ["challenge_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_challenge_participants_user_id"),
        "challenge_participants",
        ["user_id"],
        unique=False,
    )
    # batch_alter_table so the ADD COLUMN + unique constraint also works on SQLite
    # (copy-and-move); on Postgres it renders as plain ALTERs.
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("handle", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("avatar_url", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint(batch_op.f("uq_users_handle"), ["handle"])
    # NOTE: autogenerate also proposed dropping ix_walks_user_id_started_at (present in
    # the DB from 0001 but not mirrored in the ORM). Intentionally NOT dropped — the
    # history keyset query relies on it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_users_handle"), type_="unique")
        batch_op.drop_column("last_active_at")
        batch_op.drop_column("avatar_url")
        batch_op.drop_column("handle")
    op.drop_index(op.f("ix_challenge_participants_user_id"), table_name="challenge_participants")
    op.drop_index(
        op.f("ix_challenge_participants_challenge_id"), table_name="challenge_participants"
    )
    op.drop_table("challenge_participants")
    op.drop_index(op.f("ix_friendships_requester_id"), table_name="friendships")
    op.drop_index(op.f("ix_friendships_addressee_id"), table_name="friendships")
    op.drop_table("friendships")
    op.drop_index(op.f("ix_challenges_creator_id"), table_name="challenges")
    op.drop_table("challenges")
    op.drop_index(op.f("ix_activity_events_user_id"), table_name="activity_events")
    op.drop_index(op.f("ix_activity_events_created_at"), table_name="activity_events")
    op.drop_table("activity_events")
    # ### end Alembic commands ###
