"""group_streaks

Revision ID: 0005_group_streaks
Revises: 0004_community
Create Date: 2026-07-12 01:31:11.070158

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005_group_streaks"
down_revision: str | Sequence[str] | None = "0004_community"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_streaks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_group_streaks_creator_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_streaks")),
    )
    op.create_index(
        op.f("ix_group_streaks_creator_id"), "group_streaks", ["creator_id"], unique=False
    )
    op.create_table(
        "group_streak_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("streak_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["streak_id"],
            ["group_streaks.id"],
            name=op.f("fk_group_streak_members_streak_id_group_streaks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_group_streak_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_streak_members")),
        sa.UniqueConstraint("streak_id", "user_id", name=op.f("uq_group_streak_members_streak_id")),
    )
    op.create_index(
        op.f("ix_group_streak_members_streak_id"),
        "group_streak_members",
        ["streak_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_streak_members_user_id"), "group_streak_members", ["user_id"], unique=False
    )
    # (autogen also proposed dropping ix_walks_user_id_started_at — intentionally kept)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_group_streak_members_user_id"), table_name="group_streak_members")
    op.drop_index(op.f("ix_group_streak_members_streak_id"), table_name="group_streak_members")
    op.drop_table("group_streak_members")
    op.drop_index(op.f("ix_group_streaks_creator_id"), table_name="group_streaks")
    op.drop_table("group_streaks")
    # ### end Alembic commands ###
