"""walk_shared

Revision ID: 0006_walk_shared
Revises: 0005_group_streaks
Create Date: 2026-07-12 02:27:53.362123

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006_walk_shared"
down_revision: str | Sequence[str] | None = "0005_group_streaks"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "walks", sa.Column("shared", sa.Boolean(), nullable=False, server_default=sa.text("false"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("walks", "shared")
    # ### end Alembic commands ###
